=== oopsno/SingleDocker/meta.dtd
<!ELEMENT dockscallable
        (input, recognizer, postprocessor)>
        <!ELEMENT input          (#PCDATA)>
        <!ELEMENT recognizer
                (class, argument*)>
        <!ELEMENT postprocessor
                (class, argument*)>
            <!ELEMENT class    (#PCDATA)>
            <!ELEMENT argument (#PCDATA)>
                <!ATTLIST argument type CDATA "class">
                <!ATTLIST argument type CDATA "int">
                <!ATTLIST argument type CDATA "string">
                <!ATTLIST argument type CDATA "double">
                <!ATTLIST argument type CDATA "float">

=== oopsno/SingleDocker/example.xml
<!DOCTYPE dockscallable SYSTEM "meta.dtd">
<dockscallable>
    <input>data/back_fs_1387386033021_m1.wav</input>
    <recognizer>
        <class>RawGoogleRecognizer</class>
        <argument type="string">AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw</argument>
    </recognizer>
    <postprocessor>
        <class>SphinxBasedPostProcessor</class>
        <argument type="string">config/elpmaxe/elpmaxe.pgrammarsentences.xml</argument>
        <argument type="string">config/elpmaxe/elpmaxe.words</argument>
        <argument type="float">0</argument>
        <argument type="float">0</argument>
        <argument type="int">0</argument>
    </postprocessor>
</dockscallable>
